import os

from dotenv import load_dotenv


load_dotenv()


UPSTOX_CLIENT_ID = os.getenv("UPSTOX_CLIENT_ID")
UPSTOX_CLIENT_SECRET = os.getenv("UPSTOX_CLIENT_SECRET")
UPSTOX_ALGO_ACCESS_TOKEN = os.getenv("UPSTOX_ALGO_ACCESS_TOKEN")
UPSTOX_ANALYTICS_TOKEN = os.getenv("UPSTOX_ANALYTICS_TOKEN")


UPSTOX_REDIRECT_URI = os.getenv("UPSTOX_REDIRECT_URI")

ALPHA_VANTAGE_API_KEY = os.getenv("ALPHA_VANTAGE_API_KEY")
FRED_API_KEY = os.getenv("FRED_API_KEY")
MARKETAUX_API_KEY = os.getenv("MARKETAUX_API_KEY")


